stages:
  - setup
  - build
  - test

setup:
  stage: setup
  script:
    - |
      directory="./venv"
      if [ -d "$directory" ]; then
          rm -rf "$directory" 2>/dev/null || true
      fi
    - echo "Enter setup stage..."
    - directory="path/to/directory"
    - if [ -d "$directory" ]; then
      - rm -rf "$directory" 2>/dev/null || true
    - fi
    - ./scripts/install_requirements.sh
    - ls ./venv
  cache:
    paths:
      - ./venv/
  artifacts:
    paths:
      - ./venv/
  tags:
    - ar
    #- alba

build:
  stage: build
  script: 
    - echo "Enter build state..."
    - ls ./venv
    - source ~/.bashrc
    - source ./venv/bin/activate
    - ./build.sh
    - ./install.sh
  artifacts:
    paths:
      - '**/*.so'
  tags:
    - ar
    #- alba
  
test:
  stage: test
  script:
    - echo "Enter test stage..."
    - source ~/.bashrc
    - pwd
    - ls
    - ls ./venv
    - ls ./venv/bin
    - source ./venv/bin/activate
    - python3 -m pytest ./tests
  dependencies:
    - build
  artifacts:
    when: always
    paths:
      - tests/test_artifacts/*.txt
    expire_in: 4 week
  tags:
    - ar
    #- alba