stages:
  - setup
  - build
  - test

setup:
  stage: setup
  script:
    - echo "Enter setup stage..."
    - ./scripts/install_requirements.sh
  tags:
    - ar
    #- alba

build:
  stage: build
  script: 
    - echo "Enter build state..."
    - ./scripts/compile_fortran_modules.sh
  artifacts:
    paths:
       - src/fastmul.cpython-311-x86_64-linux-gnu.so
       - src/evolution_chained2.cpython-311-x86_64-linux-gnu.so
       - src/evolution_chained2_kicked.cpython-311-x86_64-linux-gnu.so
       - src/evolution.cpython-311-x86_64-linux-gnu.so
       - src/evolution2.cpython-311-x86_64-linux-gnu.so
       - src/local_op.cpython-311-x86_64-linux-gnu.so
  tags:
    - ar
    #- alba
  
test:
  stage: test
  script:
    - echo "Enter test stage..."
    - pip install pytest
    - pytest ./tests
  dependencies:
    - build
  tags:
    - ar
    #- alba