stages:
  - setup
  - build
  - test

setup:
  stage: setup
  script:
    - echo "Enter setup stage..."
    - ./scripts/install_requirements.sh
    - echo "Check python distribution:"
    - which python3
  cache:
    paths:
      - ./venv/
  artifacts:
    paths:
      - ./venv
  tags:
    - ar
    #- alba

build:
  stage: build
  script: 
    - echo "Enter build state..."
    # - echo "Check python distribution:"
    # - which python3
    #- echo "Check for intel compiler"
    # - which ifort
    - source ~/.bashrc
    - echo "#1"
    - source ./venv/bin/activate
    - echo "#2"
    - ./build.sh
    - echo "#3"
    - ./install.sh
  artifacts:
    paths:
      - '**/*.so'
  tags:
    - ar
    #- alba
  
test:
  stage: test
  script:
    - echo "Enter test stage..."
    - echo "Check python distribution:"
    - which python3
    - source ~/.bashrc
    - source ./venv/bin/activate
    - python3 -m pytest ./tests
  dependencies:
    - build
  artifacts:
    when: always
    paths:
      - tests/test_artifacts/*.txt
    expire_in: 4 week
  tags:
    - ar
    #- alba