stages:
  - setup
  - build
  - test

setup:
  stage: setup
  script:
    - echo "Enter setup stage..."
    - ./scripts/install_requirements.sh
  tags:
    #- ar
    - alba

build:
  stage: build
  script: 
    - echo "Enter build state..."
    - source ~/.bashrc
    - conda activate base
    - ./build.sh
  artifacts:
    paths:
      - '**/*.so'
  tags:
    #- ar
    - alba
  
test:
  stage: test
  script:
    - echo "Enter test stage..."
    - source ~/.bashrc
    - conda activate base
    - python3 -m pytest ./tests
    - echo "Artifact generation completed"
    - ls -lR tests/test_artifacts/
  dependencies:
    - build
  artifacts:
    paths:
      - tests/test_artifacts/*.txt
    expire_in: 4 week
  tags:
    #- ar
    - alba