stages:
  #- setup
  - build
  - test

#setup:
#  stage: setup
#  script:
#    - ./scripts/install_intel_oneapi.sh
#  tags:
#    - alba

build:
  stage: build
  script: 
    - ./scripts/compile_fortran_modules.sh
  tags:
    - alba
  
test:
  stage: test
  script:
    - echo "Running testing job."
  tags:
    - alba