stages:
  - setup
  - build
  - test

setup:
  stage: setup
  script:
    - ./scripts/install_requirements.sh
  tags:
    - ar
    #- alba

build:
  stage: build
  script: 
    - ./scripts/compile_fortran_modules.sh
  tags:
    - ar
    #- alba
  
test:
  stage: test
  script:
    - echo "Running testing job."
  tags:
    - ar
    #- alba