package:
  name: lightcones
  version: "0.0.1"

source:
  path: ../lightcones

requirements:
  host:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - python=3.12
    - numpy=2.3
    - scipy=1.15
    - meson
    - ninja

  run:
    - python=3.12
    - numpy=2.3
    - scipy=1.15